# Eureka

# InstanceId采用了随机数，确保了独一无二
eureka:
        instance:
                hostname: client
                preferIpAddress: true
                instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        client:
                service-url:
                        defaultZone: http://127.0.0.1:8761/eureka/



# Config 
spring:
        application:
                name: config-client
server:
        port: 8000

spring:
        cloud:
                config:
                        label: master
                        discovery.enabled: true
                        discovery.service-id: config-server
                        enabled: true
                        fail-fast: true
                        profile: dev

